//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Список_фильмов
    {
        public int Id { get; set; }
        public string Название_фильма { get; set; }
        public string Жанр { get; set; }
        public Nullable<int> Год { get; set; }
        public byte[] Изображение { get; set; }
        public string Путь_к_изображению { get; set; }
    }
}
